### ISSUE TITLE
Android SD card

### ISSUE THREAD

**Issue by a-dekker** [llelectronics/videoPlayer#12]
The "Show android SDCard" menu option in the filebrowser is pointing to /data/sdcard. As far as I can tell (Jolla 1/tablet) that is no longer valid in more recent Sailfish versions (or my config/mounting is very different than default). I am not sure if it can be located that easy. As I am using large parts of your filebrowser code in my mediainfo-gui app, I am considering removing this menu option for myself.

**Comment by llelectronics** [comment]
It should point to /sdcard . Got that correct in OpenDialog (Simple Filemanager) though it is wrong in the Advanced Filemanager. Need to correct that
https://github.com/llelectronics/videoPlayer/blob/master/qml/pages/fileman/OpenDialog.qml#L107
