### ISSUE TITLE
Can't switch to *.mp4 on YouTube, after *.webm decoding is failed

### ISSUE THREAD

**Issue by aptem-v** [llelectronics/videoPlayer#19]
Some YouTube videos not playing on my device (probably due to hybrys adaptation), because it selected WebM format by default, but LLs Player not trying switch to MP4, even it available.

Can I somehow switch LLs Player to prefer mp4 format?

I tryed to do it manually:
$ youtube-dl --list-formats URL
(shows mp4 variants are available)
$ youtube-dl --format mp4 URL
Downloaded .mp4 file was successfully played by LLs Player.

**Comment by llelectronics** [comment]
The Player by default prefers the MP4 format always.

**Comment by aptem-v** [comment]
Sorry, I started looking for a solution without looking at the log.
In fact, this is a more strange case:

r[8620]: [D] :180 - [yt.js]: Video in format MP4 720p found with direct URL:
...
r[8620]: [W] unknown:0 - Warning: "No decoder available for type 'text/html'."
r[8620]: [W] unknown:0 - Error: "Your GStreamer installation is missing a plug-in."

After "Dismiss" tapped, it retryed and showed the video finally. This time.
(Not yesterday, when there was nothing else. This video is new, and probably, yesterday it was not converted yet, but converted now. Next time, I will check the log immediately, after it happened.)

**Comment by llelectronics** [comment]
Ah ok. Thanks for reporting back.
