### ISSUE TITLE
Localization is needed

### ISSUE THREAD

**Issue by TylerTemp** [llelectronics/videoPlayer#2]
Could you support localization (e.g. using [transifex](https://www.transifex.com))?

**Comment by llelectronics** [comment]
This will come later. First I need the player to be feature complete.

**Comment by d9h02f** [comment]
Any progress on this front?

**Comment by llelectronics** [comment]
Not atm. But I am planning to add localization this year. Just need some time for actually doing it.

**Comment by dikonov** [comment]
Please, do it! Sailfish OS 3.0 is due soon and I would like to see this great app fully translated and accessible to users that do not understand English.

**Comment by llelectronics** [comment]
Added translation support finally: https://github.com/llelectronics/videoPlayer/commit/587a4ea6ee13767172b88f3ed2879164bb4625e7
