### ISSUE TITLE
Add support for SSA subtitles

### ISSUE THREAD

**Issue by pstopkin** [llelectronics/videoPlayer#21]
Hi,

I've customized scripts for ssa/ass-files loading and simple time-overlapped text stacking. I hope, updated scripts (getsubtitles.js and checksubtitles.js) will be useful. It was tested on SailfishOS 2.1.2.3, Inoi R7 phone.

What's added:
- select available subtitles file from the list: *.srt, *.ssa, *.ass;
- parse SubStation Alpha subtitles, text only, without styles;
- quick search and stacking current subtitles by time.

[helper.tar.gz](https://github.com/llelectronics/videoPlayer/files/1497892/helper.tar.gz)

**Comment by llelectronics** [comment]
Wonderful. Thank you very much for your contribution.
