### ISSUE TITLE
Crash when opening pls playlist file

### ISSUE THREAD

**Issue by OH1KK** [llelectronics/videoPlayer#22]
LLs Video Player v1.9

I tried to make playlist for ubiquiti rtsp webcams and open it with LLs Video player. When I try to load playlist player crashes.

Steps to reproduce crash

1. Open application
2. Select Playlists
3. Load Playlist
4. select  bonkkitallennin.pls

crash.

[F] unknown:0 - ASSERT: "uint(i) < uint(size())" in file /usr/include/qt5/QtCore/qstring.h, line 868
Aborted

Expected behaviour
- Load playlist or display error that playlist is invalid

[bonkkitallennin.pls.txt](https://github.com/llelectronics/videoPlayer/files/1500227/bonkkitallennin.pls.txt)

added .txt extension to playlist attachment for github

**Comment by OH1KK** [comment]
Launching streams direcly from console

 /usr/bin/harbour-videoPlayer rtsp://172.16.50.8:7447/59a97b79e4b0518d34cdd972_1

Works ok. Video and audio works. So this feels like playlist issue.

**Comment by llelectronics** [comment]
Thanks for reporting. 
The issue had nothing to do with rtsp streams but rather with the parser for the .pls files. 
The empty newlines at the end of your playlists made it crash as it did not properly handle empty lines at all. 
This is all fixed now. 

Thanks again for reporting.
