### ISSUE TITLE
integrate mediathekview 

### ISSUE THREAD

**Issue by fuchsmich** [llelectronics/videoPlayer#27]
Hi Leszek,

Do you think it makes sense integrating mediathekview, like you integrated youtube?

greetz, Michael.

**Comment by llelectronics** [comment]
There is a new app for mediathekview specifically. I leave it as enhancement here for now. Lets see how this other player will evolve.

**Comment by llelectronics** [comment]
https://github.com/zwieberl/harbour-fishtheke

**Comment by fuchsmich** [comment]
Haha, nice name for the app.

**Comment by zwieberl** [comment]
Hi, author of fishtheke here. 
We have had a quite [lengthy discussion](https://github.com/zwieberl/harbour-fishtheke/issues/9) about how to integrate with videoPlayer.
I've come down to using dbus, if possible. This already works for "Jolla gallery" and [jupii](https://github.com/mkiol/Jupii), which both provide a way to play/add URLs via dbus (jupii can serve as a reference, as it has a very simple, but sufficient interface). 

It would be really nice, if videoPlayer could provide a dbus-interface similar to Jolla gallery, which is even started automatically if not already running. Then any app (e.g. fishtheke) could simply check if videoPlayer is installed, and if so, send URLs/Files to it to be played.

Might this be feasable?

**Comment by llelectronics** [comment]
I am not planning to add dbus stuff but I am open for pull requests for people that like to do that. 
The approach currently used also by webcat is to call LLs Video Player with the URL as argument. 
I saw that it was discussed and not choosen as you want to have this universal accessible also for other applications. 
IMHO all video players should be able to accept URLs as arguments.

**Comment by zwieberl** [comment]
Forgot to mention: The latest version of Fishtheke now starts videoPlayer as Webcat does (via commandline).
