### ISSUE TITLE
No update Yt-Dl feedback, app stays in update state infinitely

### ISSUE THREAD

**Issue by Pohli** [llelectronics/videoPlayer#28]
Today I tapped on Update Youtube-Dl in Settings for the first time. The background got darkened and moved back to main page. In foreground is a never-ending throbber. App was still responsive although darkened, is this intended? I had to close app and start again.
There should be some message about what has gone wrong or any other kind of feedback.

Jolla Phone with SFOS 3.0.0.8 and LLs Video Player 1.9

**Comment by llelectronics** [comment]
It should you after the update performed well or if it fails.

**Comment by Pohli** [comment]
Tested again, after more than 20 min I cancelled. Console output doesn't say anything about update procedure:

[nemo@Sailfish ~]$ harbour-videoPlayer
[D] unknown:0 - QML debugging is enabled. Only use this in a safe environment.
[D] unknown:0 - Using Wayland-EGL
[W] unknown:0 - Could not find any zN.M subdirs!
[W] unknown:0 - Theme dir "/usr/share/themes/jolla-ambient/meegotouch/z1.0/" does not exist
[W] unknown:0 - Both point size and pixel size set. Using pixel size.
[W] unknown:38 - file:///usr/lib/qt5/qml/Sailfish/Silica/private/Util.js:38: TypeError: Cannot read proper
ty 'parent' of null
[W] unknown:195 - file:///usr/lib/qt5/qml/Sailfish/Silica/DialogHeader.qml:195: TypeError: Cannot read pro
perty 'backIndicatorDown' of null
[W] unknown:190 - file:///usr/lib/qt5/qml/Sailfish/Silica/DialogHeader.qml:190: TypeError: Cannot read pro
perty 'backIndicatorDown' of null
[W] unknown:248 - file:///usr/lib/qt5/qml/Sailfish/Silica/DialogHeader.qml:248: TypeError: Cannot read pro
perty 'forwardIndicatorDown' of null
[W] unknown:243 - file:///usr/lib/qt5/qml/Sailfish/Silica/DialogHeader.qml:243: TypeError: Cannot read pro
perty 'forwardIndicatorDown' of null

**Comment by llelectronics** [comment]
That is correct. You won't see any output in the terminal. 
Is the youtube-dl binary (python file) available in **~/.local/share/harbour-videoPlayer/harbour-videoPlayer/** and is it marked executable (it should)

**Comment by llelectronics** [comment]
Then it should update just fine if your internet connection is working. It might be that the youtube-dl app itself hangs if you have no internet connection which causes the progress loop not to end.

**Comment by Pohli** [comment]
I rebooted my phone and tried again but still same problem. My WiFi connection is fine, I'm posting from the same phone right now.

**Comment by llelectronics** [comment]
What happens when you manually try updating calling the youtube-dl binary with the -U option?

**Comment by Pohli** [comment]
Please have a look if I did something wrong?

[nemo@Sailfish ~]$ cd .local/share/harbour-videoPlayer/harb
our-videoPlayer/
[nemo@Sailfish harbour-videoPlayer]$ ls
QML  youtube-dl
[nemo@Sailfish harbour-videoPlayer]$ youtube-dl --help
bash: youtube-dl: command not found
[nemo@Sailfish harbour-videoPlayer]$ ./youtube-dl --help
/usr/bin/env: python: No such file or directory
[nemo@Sailfish harbour-videoPlayer]$ ./youtube-dl -U
/usr/bin/env: python: No such file or directory

**Comment by llelectronics** [comment]
So the issue is that you are missing python. Weird. It is a dependency of LLs Video Player. 
Just manually install python with 
devel-su pkcon install python

**Comment by Pohli** [comment]
Thanks, now update worked.
But I get this Ressource Error (spelling is wrong, should be Resource) with every YouTube video so far. Do I need to be logged in?

**Comment by llelectronics** [comment]
Try non DRM videos. That should play fine. Otherwise you can find the ytdl option in the pulley menu of the video to try the (including DRM) video grabbing with youtube-dl
