### ISSUE TITLE
Command line option to force youtube-dl resolver use

### ISSUE THREAD

**Issue by nodevel** [llelectronics/videoPlayer#3]
The command line argument functionality of harbour-videoPlayer is very useful if one doesn't want to re-implement the whole Video Player in an app, but make use of this existing player.

However, with the nice inclusion of the youtube-dl resolver library, it would be great if one could launch the player with an argument that would force the player to try youtube-dl on the url first, just like it currently works with Youtube videos. The functionality is already there, so this would just allow more flexibility.

For example:
`harbour-videoPlayer -y http://my.video/url/`

**Comment by llelectronics** [comment]
Fixed with https://github.com/llelectronics/videoPlayer/commit/692af0d37dd7762071c0557f5445d1bc7b5144b2
It will run everything with an url through ytdl except for youtube.

**Comment by nodevel** [comment]
Perfect, thank you! Now it behaves more or less like mpv.
