### ISSUE TITLE
Encrypted/unlocked sdcard not recognized

### ISSUE THREAD

**Issue by supremesyntax** [llelectronics/videoPlayer#36]
With Sfos 3.0.1.11 i have formatted and encrypted the microsd card successfully from the sfos ui.

It is automatically mounted on /var/run/media/nemo/xyz while xyz is the name that you chose for the card when formatting it. I guess if you do not chose a name that will be the uuid (not tested, wild guessing)

The icon in your application representing the sdcard is greyed out and does not link to the card.
(You can get there with the file browser by selecting the path mentioned above though.)

**Comment by llelectronics** [comment]
Currently the sd card check checks for mmcblk1p1. 
I think on the encrypted partition this might be p2 or p3 or something else. 
I added this commit to see if it could fix the issue. It would return the path of the mmcblk1's last partition: https://github.com/llelectronics/videoPlayer/commit/debc814dd44ce5a7581a3943b8b49306fe72b783

Please tell me if it works for you.
