### ISSUE TITLE
Translations

### ISSUE THREAD

**Issue by ktrace** [llelectronics/videoPlayer#37]
I think translation via Weblate (https://hosted.weblate.org/projects/) or transifex (https://www.transifex.com/) will be very useful.

**Comment by llelectronics** [comment]
I had bad experience with transifex so far. Thats why I don't want to use it here again. The other one I don't know yet. Need to check this first.

**Comment by ktrace** [comment]
Commits from service look like: https://github.com/gammu/gammu/commits/master
It maybe selfhosted. It has command line utility. It not need registration at all (acc on GH enough).

**Comment by dikonov** [comment]
I have added a Russian translation, but I could not test it by adding a .qm resource file and running the app with the changed strings before release. The current package does not contain a folder for translation files (.qm). Are there any pre-release builds?

**Comment by llelectronics** [comment]
Problem should be fixed
