### ISSUE TITLE
Subtitles font size is too small on a bigger resolution device

### ISSUE THREAD

**Issue by topiasv** [llelectronics/videoPlayer#4]
Just tested the player on my Jolla Tablet and noticed that the font size for the subtitles is way too small. Theme object small/medium/large etc sizes should be used instead of points to improve scalability.

**Comment by llelectronics** [comment]
You are absolutely right. 
Fixed with commit: https://github.com/llelectronics/videoPlayer/commit/1c88af67abbdede3903f8aaab8d53653a7426c3e
