### ISSUE TITLE
Add another way to search the video

### ISSUE THREAD

**Issue by Pohli** [llelectronics/videoPlayer#44]
As someone else already mentioned on OpenRepos recently it's a bit tricky to search a video, even though the time display size is temporarily increased while searching. The time is sometimes still covered by one's finger (at least partially) and not readable properly. One solution would be to display the time somewhere else on the screen as long as one is searching.
Another solution would be to add another way of search function like it's done in other video players like VLC Player for Android. There you can search by tapping approximately in the centre of the screen and swipe more or less far to the right or left to go forward or rewind more or less fast respectively. It also shows the absolute and relative time. Swiping up and down changes sound volume btw.

**Comment by llelectronics** [comment]
> One solution would be to display the time somewhere else on the screen as long as one is searching.

Its a default Silica element that I use here. It needs fixing in Silica. I am not willing to add some extra magic to fix the behavior that should be fixed upstream. 

> Another solution would be to add another way of search function like it's done in other video players like VLC Player for Android. There you can search by tapping approximately in the centre of the screen and swipe more or less far to the right or left to go forward or rewind more or less fast respectively

That is an interesting approach but collides with the swipe gestures for pages and also too much jumping in the timeline crashes gstreamer/qtmultimedia

**Comment by llelectronics** [comment]
Implemented with: https://github.com/llelectronics/videoPlayer/commit/48689290e67ae91615bd22a302990ca8d0943277
