### ISSUE TITLE
Can't select video at bottom of History page in landscape view

### ISSUE THREAD

**Issue by Pohli** [llelectronics/videoPlayer#47]
If a video is still active in background it'll prevent me from selecting a video at the bottom of the History page when in landscape mode.

![Screenshot_20190512_001](https://user-images.githubusercontent.com/26346589/57652816-b1e91280-75d0-11e9-8298-233d505b5def.png)

**Comment by llelectronics** [comment]
Please attach the screenshot

**Comment by Pohli** [comment]
Screenshot added in my initial comment.
Btw: What is the display of current video at the bottom good for? (I think you added that in one of the recently published versions.) If I tap the play button only sound playback will start but it won't return to video view.

**Comment by llelectronics** [comment]
It is a mini player for sound playback mostly.
Also regarding the screenshot. You can simply swipe away the mini player to gain access to the history bottom entries.

**Comment by Pohli** [comment]
Yeah, sometimes I don't see the obvious.

So if a video is still kind of loaded in background (can be played with mini player) is there a way to return to video view to resume playback of that video? I already asked this on OpenRepos but your answer sounded ironic (video player gets destroyed) or do I misunderstand?

**Comment by llelectronics** [comment]
The mini Player is an audio only player. So you really can't go back to the video player as this is really destroyed.
