### ISSUE TITLE
Feature: Add support for MPRIS2 controlling

### ISSUE THREAD

**Issue by schmittlauch** [llelectronics/videoPlayer#5]
It'd be great if the videoPlayer offered an MPRIS2 compatible DBus interface so it can be controlled with either the lockscreen controls or bluetooth headphones.

**Comment by llelectronics** [comment]
MprisPlayer seems to be broken at the moment. At least the code is basically in there but besides pausing and hitting next and prev playing does not do anything as it seems.

**Comment by llelectronics** [comment]
This commit fixes the play not functioning thing: https://github.com/llelectronics/videoPlayer/commit/79b5d3ef9c05527b2a5be1b2383d31f13c7d7841
Though title showing and prev/next button showing is still a hit and miss. 
It seems like MprisPlayer does not like dynamically changing stuff. Need to take a look if I am able to change this somehow.
