### ISSUE TITLE
feature request: Jupii DLNA compatible

### ISSUE THREAD

**Issue by GNUuser** [llelectronics/videoPlayer#61]
Like microtube

**Comment by llelectronics** [comment]
Code added. Please test if it works. I don't have a device here to test this.

**Comment by GNUuser** [comment]
Thank you so much for adding this feature, I am going to buy a pizza for you righ now for paypal.
I will test with you release new version.

**Comment by GNUuser** [comment]
> Thank you so much for adding this feature, I am going to buy a pizza for you righ now for paypal.
> I will test when you release new version.

DONE: Id. de transacción: 80S262401D7098411

**Comment by llelectronics** [comment]
Thank you. Arrived :)

**Comment by GNUuser** [comment]
Hi @llelectronics  
When new release? i can not wait...

**Comment by llelectronics** [comment]
When its ready. I want to do some changes still

**Comment by GNUuser** [comment]
come on... SF3.4 is here already.
