### ISSUE TITLE
Media buttons 

### ISSUE THREAD

**Issue by OhDaeto** [llelectronics/videoPlayer#8]
Sorry, how you did support for media control on lockscreen?

**Comment by llelectronics** [comment]
Basically you need to import mpris support from Nemo. 
See https://github.com/llelectronics/videoPlayer/blob/master/qml/pages/videoPlayer.qml#L7

And MprisPlayer here: https://github.com/llelectronics/videoPlayer/blob/master/qml/pages/videoPlayer.qml#L848
