### ISSUE TITLE
App freeze

### ISSUE THREAD

**Issue by Skillmon** [llelectronics/videoPlayer#9]
Today I got a freeze of the latest version on OpenRepos on my Jolla 1. The freeze occured when I paused a video then closed the playback with swipe gesture to go back to integrated filebrowser. In the moment I swiped back to filebrowser the phone orientation changed from landscape to portrait. I got to the filebrowser but all entries were grayed out. After 10 - 20 seconds nothing had changed from that so I closed the app (had gone to homescreen before and reopened the app several times). When I tried to reconstruct the situation I didn't get the timing "right". So it seems like this is really rare and I doubt that I will encounter the bug again.

**Comment by llelectronics** [comment]
I think this is a random crash if not. Feel free to open it again.
